### ISSUE TITLE
Job initialization changes data type of keys in nested dictionaries

### ISSUE THREAD

**Issue by sagnik** [glotzerlab/signac#861]
### Description

invoking signac is changing my job config dict.

### To reproduce

1. create a new dir: `signac-mwe`
2. `signac init signiacmwe`
3. create the following files as `signac-mwe.py` and `signac-mwe.yml`

```python
import argparse
from yaml import safe_load
from pprint import pprint
import signac

parser = argparse.ArgumentParser("signac-mwe")
parser.add_argument("config_file")
args = parser.parse_args()
configs = safe_load(open(args.config_file))
pprint(configs["datasets"])
project = signac.get_project("signacmwe")
job = project.open_job(configs)
job.init()
pprint(configs["datasets"])
```

```yaml
datasets:
  snli-hfd:
    name: snli-hfd
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    label_2_id:
      entailment: 0
      neutral: 1
      contradiction: 2
    phase: test
    start: 20
    end: 41
    randomize: false
```

4. Here's the output:
```
{'snli-hfd': {'end': 41,
              'id_2_label': {0: 'entailment', 1: 'neutral', 2: 'contradiction'},
              'label_2_id': {'contradiction': 2, 'entailment': 0, 'neutral': 1},
              'name': 'snli-hfd',
              'phase': 'test',
              'randomize': False,
              'start': 20}}
{'snli-hfd': {'end': 41,
              'id_2_label': {'0': 'entailment',
                             '1': 'neutral',
                             '2': 'contradiction'},
              'label_2_id': {'contradiction': 2, 'entailment': 0, 'neutral': 1},
              'name': 'snli-hfd',
              'phase': 'test',
              'randomize': False,
              'start': 20}}
```
I am printing the config dict before and after initializing the project and the job. The types of the keys in the `id_2_label` dict have changed from `int` to `str` after the initialization. That should not happen.

### Error output

NA

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Ubuntu 20.04.1 LTS
 - Version of Python [e.g. 3.7]: 3.7.11
 - Version of signac [e.g. 1.0]: 1.7.0
